export const STEPS = [
  {
    id: 'idea',
    title: 'Encuentra y define tu idea',
    short: 'Ejercicio guiado + IA',
    intro: 'Pasa de "quiero emprender" a una idea concreta que puedas explicar en una frase.',
    time: '≈ 2 días',
    tip: 'Empieza por problemas que tú o la gente cercana viven a diario. Las mejores ideas resuelven algo molesto y frecuente.',
    activities: [
      { id: 'idea-1', type: 'read', title: 'De dónde salen las buenas ideas', meta: 'Lectura · 4 min',
        body: 'La mayoría de negocios exitosos no nacen de una idea genial, sino de un problema bien observado. Fíjate en lo que te molesta a ti, a tu familia o a tus compañeros: filas, cosas caras, servicios lentos, productos que no existen cerca. Si un problema se repite y la gente ya gasta dinero o tiempo intentando resolverlo, ahí hay una oportunidad.' },
      { id: 'idea-2', type: 'exercise', title: 'Haz una lista de 10 problemas que ves a tu alrededor', meta: 'Ejercicio · 15 min',
        body: 'Escribe 10 problemas concretos que hayas visto esta semana. No los filtres todavía: anota también los que parezcan pequeños. Al lado de cada uno, marca quién lo sufre y qué tan seguido.' },
      { id: 'idea-3', type: 'exercise', title: 'Elige uno y escribe tu idea en una frase', meta: 'Ejercicio · 10 min',
        body: 'Elige el problema que más se repite y que te emocione resolver. Escribe tu idea así: "Ayudo a [quién] a [resolver qué] con [tu solución]". Si no cabe en una frase, todavía no está clara.' },
      { id: 'idea-4', type: 'ai', title: 'Pídele a la IA que critique tu idea', meta: 'Asistente · 5 min',
        body: 'Pega tu frase en el asistente y pídele que te diga los 3 mayores riesgos de la idea. No es para desanimarte: es para saber qué validar primero.',
        ask: 'Esta es mi idea de negocio: … ¿Cuáles son los 3 mayores riesgos?' },
    ],
  },
  {
    id: 'validar',
    title: 'Valida con clientes reales',
    short: 'Guion de entrevista incluido',
    intro: 'Antes de invertir dinero, confirma que alguien de verdad tiene el problema y pagaría por resolverlo.',
    time: '≈ 3 días',
    tip: 'No preguntes "¿lo comprarías?". Pregunta cómo resuelven hoy ese problema y cuánto les cuesta.',
    template: 'guion',
    activities: [
      { id: 'val-1', type: 'read', title: 'Por qué validar antes de invertir', meta: 'Lectura · 4 min',
        body: 'Validar es comprobar con personas reales que el problema existe y que les importa lo suficiente como para pagar. Cinco conversaciones honestas te ahorran meses de trabajo y dinero en algo que nadie quiere.' },
      { id: 'val-2', type: 'exercise', title: 'Define a quién le vas a preguntar', meta: 'Ejercicio · 10 min',
        body: 'Describe a tu cliente ideal: edad, dónde vive, qué hace y dónde lo puedes encontrar. Luego escribe los nombres de 5 personas reales que encajen y que puedas contactar esta semana.' },
      { id: 'val-3', type: 'template', title: 'Entrevista a 5 posibles clientes', meta: 'Con el guion de entrevista', template: 'guion',
        body: 'Usa el guion de entrevista. Escucha más de lo que hablas y anota las frases exactas que te digan: te servirán para tu marketing después.' },
      { id: 'val-4', type: 'ai', title: 'Analiza las respuestas con la IA', meta: 'Asistente · 5 min',
        body: 'Resume lo que te dijeron y pídele al asistente que encuentre patrones: ¿el problema se repite? ¿alguien ya paga por resolverlo?',
        ask: 'Entrevisté a 5 personas y me dijeron esto: … ¿Qué patrones ves?' },
    ],
  },
  {
    id: 'plan',
    title: 'Arma tu plan de negocio',
    short: 'Plantilla de 1 página',
    intro: 'Ordena en una sola página quién es tu cliente, qué le ofreces y cómo vas a ganar dinero.',
    time: '≈ 1 día',
    tip: 'Un plan corto que actualizas cada mes vale más que un documento de 40 páginas que nadie lee.',
    template: 'plan',
    activities: [
      { id: 'plan-1', type: 'read', title: 'Qué debe tener un plan sencillo', meta: 'Lectura · 3 min',
        body: 'Un buen plan inicial responde 5 preguntas: qué problema resuelves, para quién, cuál es tu solución, cómo ganas dinero y por qué canales llegas a tus clientes. Con eso basta para empezar.' },
      { id: 'plan-2', type: 'template', title: 'Llena el plan de negocio en 1 página', meta: 'Plantilla · 20 min', template: 'plan',
        body: 'Abre la plantilla y responde cada bloque en pocas líneas. Usa lo que aprendiste en las entrevistas.' },
      { id: 'plan-3', type: 'ai', title: 'Pide a la IA que revise tu plan', meta: 'Asistente · 5 min',
        body: 'Pega tu plan en el asistente y pregúntale qué parte está más débil.',
        ask: '¿Puedes revisar mi plan de negocio y decirme qué parte está más débil?' },
    ],
  },
  {
    id: 'finanzas',
    title: 'Haz cuentas: costos y precios',
    short: 'Plantilla de finanzas',
    intro: 'Calcula cuánto te cuesta tu producto, cuánto cobrar y cuánto necesitas para arrancar.',
    time: '≈ 1 día',
    tip: 'Incluye tu tiempo en los costos. Si no te pagas a ti, el negocio no es sostenible.',
    template: 'precio',
    activities: [
      { id: 'fin-1', type: 'read', title: 'Costos fijos y costos variables', meta: 'Lectura · 4 min',
        body: 'Los costos variables cambian con cada unidad que vendes (materiales, empaque, envío). Los fijos los pagas vendas o no (arriendo, internet, plataformas). Tu precio debe cubrir los variables con margen, y las ventas del mes deben cubrir los fijos.' },
      { id: 'fin-2', type: 'template', title: 'Calcula el precio de tu producto', meta: 'Plantilla · 10 min', template: 'precio',
        body: 'Usa la calculadora para sumar tus costos por unidad y elegir un margen de ganancia.' },
      { id: 'fin-3', type: 'template', title: 'Arma tu presupuesto inicial', meta: 'Plantilla · 15 min', template: 'presupuesto',
        body: 'Anota todo lo que necesitas comprar o pagar antes de tu primera venta. Así sabrás cuánto dinero necesitas para arrancar.' },
    ],
  },
  {
    id: 'formalizar',
    title: 'Formaliza tu negocio',
    short: 'RUT, Cámara de Comercio, DIAN',
    intro: 'Conoce los trámites básicos para operar legalmente en Colombia y cuándo hacer cada uno.',
    time: '≈ 1 semana',
    tip: 'No necesitas hacer todos los trámites el primer día. Empieza por el RUT y avanza a medida que vendas.',
    activities: [
      { id: 'leg-1', type: 'read', title: 'Qué trámites necesitas y cuándo', meta: 'Lectura · 5 min',
        body: 'El primer paso suele ser el RUT (Registro Único Tributario) ante la DIAN. Cuando ya ejerces el comercio de forma habitual, debes registrarte en la Cámara de Comercio (matrícula mercantil), que se renueva cada año. Algunos sectores, como alimentos, necesitan permisos sanitarios adicionales.' },
      { id: 'leg-2', type: 'exercise', title: 'Saca tu RUT en la DIAN', meta: 'Trámite en línea · gratis',
        body: 'Entra a dian.gov.co, busca "Inscripción RUT" y sigue los pasos con tu cédula y un correo. El trámite es gratuito.' },
      { id: 'leg-3', type: 'exercise', title: 'Revisa si necesitas registro en Cámara de Comercio', meta: 'Ejercicio · 10 min',
        body: 'Busca la Cámara de Comercio de tu ciudad y revisa los requisitos para persona natural o para crear una SAS. Anota los costos para tu presupuesto.' },
      { id: 'leg-4', type: 'ai', title: 'Pregunta por los permisos de tu sector', meta: 'Asistente · 5 min',
        body: 'Cada tipo de negocio puede tener permisos especiales. Pregúntale al asistente por el tuyo.',
        ask: '¿Qué permisos especiales necesito para mi tipo de negocio?' },
    ],
  },
  {
    id: 'clientes',
    title: 'Consigue tus primeros clientes',
    short: 'Redes y marketing básico',
    intro: 'Haz tus primeras ventas con lo que ya tienes: tu red de contactos y las redes sociales.',
    time: '≈ 2 semanas',
    tip: 'Tus primeros 10 clientes casi nunca llegan por publicidad pagada. Llegan por recomendación y por hablar directamente con la gente.',
    activities: [
      { id: 'cli-1', type: 'read', title: 'Tus primeros 10 clientes están cerca', meta: 'Lectura · 4 min',
        body: 'Empieza por tu círculo: amigos, familia, compañeros y las personas que entrevistaste. Ofréceles probar tu producto y pídeles que te recomienden si les gustó.' },
      { id: 'cli-2', type: 'exercise', title: 'Crea el perfil de tu negocio', meta: 'Ejercicio · 20 min',
        body: 'Abre una cuenta de Instagram o WhatsApp Business para tu negocio. Usa tu frase de una línea como descripción y pon fotos reales de tu producto.' },
      { id: 'cli-3', type: 'template', title: 'Planea 2 semanas de publicaciones', meta: 'Plantilla · 15 min', template: 'contenido',
        body: 'Organiza qué vas a publicar cada día. Mezcla producto, detrás de cámaras y testimonios de clientes.' },
      { id: 'cli-4', type: 'exercise', title: 'Consigue tu primera venta', meta: 'Meta',
        body: 'Escríbeles directamente a 10 personas que podrían comprarte. La primera venta es la más difícil y la más importante.' },
    ],
  },
]

export const TEMPLATES = [
  { id: 'plan', title: 'Plan de negocio en 1 página', cat: 'Plan' },
  { id: 'precio', title: 'Calculadora de costos y precio', cat: 'Finanzas' },
  { id: 'presupuesto', title: 'Presupuesto inicial', cat: 'Finanzas' },
  { id: 'contenido', title: 'Calendario de contenido para redes', cat: 'Marketing', pro: true },
  { id: 'guion', title: 'Guion para entrevistar clientes', cat: 'Plan' },
  { id: 'flujo', title: 'Flujo de caja mensual', cat: 'Finanzas', pro: true },
]

export const PLAN_BLOCKS = [
  { id: 'problema', label: 'Problema', hint: '¿Qué problema resuelves?' },
  { id: 'cliente', label: 'Cliente', hint: '¿Quién tiene ese problema?' },
  { id: 'solucion', label: 'Solución', hint: '¿Qué le ofreces?' },
  { id: 'ingresos', label: 'Cómo ganas dinero', hint: '¿Qué cobras y cuánto?' },
  { id: 'canales', label: 'Canales', hint: '¿Cómo llegas a tus clientes?' },
]

export const INTERVIEW_QUESTIONS = [
  'Cuéntame sobre la última vez que tuviste este problema.',
  '¿Qué fue lo más difícil o molesto de esa situación?',
  '¿Cómo lo resolviste?',
  '¿Cuánto tiempo o dinero te costó resolverlo?',
  '¿Qué no te gusta de las soluciones que has probado?',
  '¿Con qué frecuencia te pasa?',
  'Si pudieras arreglarlo con una varita mágica, ¿cómo sería?',
  '¿Has buscado otras alternativas? ¿Cuáles?',
  '¿Conoces a alguien más que tenga este problema?',
  '¿Puedo volver a contactarte cuando tenga algo para mostrarte?',
]
